### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by regnans** [ess-dive-workspace/essdive-workspace-guide#8]
**Submitter**: Kim 

I suggest the following: The link from the README TOC to Chapter 2 Starting a new repository is broken, and returned a 404 error. :(   The links for other chapters are all OK :) 

https://github.com/ess-dive-workspace/essdive-workspace-guide/blob/main/02__new_repository.md

**Comment by wavingtowaves** [comment]
Thanks for catching that @regnans! Glad the other links are working :) I'd like to spend a bit more time working on this guide in the future. Definitely a work in progress, but I'm hoping it'll be useful for people!
